### ISSUE TITLE
Which type of bootstrap?

### ISSUE THREAD

**Issue by Federico2111** [XiangwenWang/correlation#1]
Hello, 

Thanks for creating this Python library.

I just wanted to ask if the bootstrap method that you used, and that you call “naive”, is the one which is referred in the literature as "non-studentized pivotal (basic)" bootstrap method or is it the "basic percentile" bootstrap method?

Please, let me know. 

Thanks 

Federico

**Comment by XiangwenWang** [comment]
Hi Federico,

Sorry for my late reply. I used the“percentile bootstrap”, one of the most naive bootstrapping methods. I think it is (slightly) different from the non-studentized pivotal method you mentioned. 

Best Regards,
Xiangwen Wang

**Comment by Federico2111** [comment]
Thank you!

Federico
