### ISSUE TITLE
Are the p-values on correlation coefficients accurate?

### ISSUE THREAD

**Issue by Federico2111** [XiangwenWang/correlation#2]
In the Spearman correlation scipy library, they say that "The p-values are not entirely reliable but are probably reasonable for datasets larger than 500 or so."
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html

In this library, how are the p-values on (all) correlation coefficients calculated? Similarly to scipy? What’s their reliability?

Thanks for your help.

**Comment by XiangwenWang** [comment]
I actually used scipy.stats to compute the p-values. With that said, you can also use bootstrapping to compute a p-value for spearman correlation, but it also requires a considerable sample size to generate a reasonable p-value.

**Comment by Federico2111** [comment]
Thanks for clarifying. Probably you should make a comment about this on the library description. Hope this helps. I will close this issue.
